class AddMoreCols < ActiveRecord::Migration
  def change
    add_column :countries, :rank_ec, :integer
    add_column :countries, :conjuncture, :integer
    add_column :countries, :sustainability, :integer
    add_column :countries, :rank_l, :integer
    add_column :countries, :entrywages, :integer
    add_column :countries, :skills, :integer
    add_column :countries, :wages, :integer
    add_column :countries, :financial_vulnerability, :integer
    add_column :countries, :housing, :integer
    add_column :countries, :rank_pol, :integer
    add_column :countries, :marginal, :integer
    add_column :countries, :implicitweight, :integer
    add_column :countries, :policymaking, :integer
    add_column :countries, :rank_pf, :integer
    add_column :countries, :explicit, :integer
    add_column :countries, :implicit, :integer
    add_column :countries, :rank_hwb, :integer
    add_column :countries, :social, :integer
    add_column :countries, :individual, :integer
    add_column :countries, :freedom, :integer
    add_column :countries, :rank_e, :integer
    add_column :countries, :access, :integer
    add_column :countries, :early_quality, :integer
    add_column :countries, :transition, :integer
    add_column :countries, :conditions, :integer
    add_column :countries, :rank_j, :integer
    add_column :countries, :unemployment, :integer
    add_column :countries, :entrepreneurship, :integer
    add_column :countries, :underemployment, :integer
    add_column :countries, :exclusion, :integer
    add_column :countries, :rank_u, :integer
    add_column :countries, :completion, :integer
    add_column :countries, :univ_quality, :integer
    add_column :countries, :cost, :integer
    add_column :countries, :vocational, :integer
  end
end
